language: node_js

node_js:
  - "node"
  - "6.4"
  - "5.3"
  - "4.5"
  - "4.2"
  - "iojs"
  - "0.12"

#addons:
#  code_climate:
#    repo_token:

#after_script:
#  - npm run coverage
#  - codeclimate-test-reporter < coverage/lcov.info
